FROM node:14-alpine
ENV HOME=/home/node
EXPOSE 3000
RUN yarn global add vercel && \
    yarn cache clean && \
    chown -R node:node $HOME
USER node
WORKDIR $HOME
CMD cd /home/node && vercel dev --token $TOKEN
