version: '3.6'
services:
  vercel:
    build:
      context: .
      dockerfile: Dockerfile-vercel-dev
    environment:
      TOKEN: lWCzZfvEJY2HA6A20dMnuHRR
    ports:
      - "3000:3000"
    volumes:
    - .:/home/node
  firebase:
    build:
      context: .
      dockerfile: Dockerfile-firebase
      args:
        VERSION: 9.3.0
    ports:
    - "24000:24000"
    - "25000:25000"
    - "25001:25001"
    - "28080:28080"
    - "28085:28085"
    - "29000:29000"
    - "9005:9005"
    - "29099:29099"
    environment:
      FIREBASE_TOOLS_VERSION: 9.3.0
    volumes:
    - .:/home/node
  postgres:
    image: postgres:12
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecret
      HASURA_GRAPHQL_AUTH_HOOK: http://vercel:3000/api/user/validate
volumes:
  db_data:
